/**
 * FINANCE FIXTURE STATE
 *
 * Single source of truth for all mock financial data.
 * Values follow the final design reference (layout + data).
 * All UI values are DERIVED from this state — never hardcoded in components.
 */

import type {
  Account,
  AgendaItem,
  ArchivedAgenda,
  BillDue,
  PosItem,
  Transaction,
} from './types';

export interface FinanceFixture {
  accounts: Account[];
  billsDue: BillDue[];
  posItems: PosItem[];
  agendas: AgendaItem[];
  archivedAgendas: ArchivedAgenda[];
  transactions: Transaction[];
  /** Komitmen rutin yang mengurangi Uang Bebas (dari formula modul Uang Bebas). */
  savingsCommitment: number;
}

export const financeFixture: FinanceFixture = {
  accounts: [
    {
      id: 'acct-seabank',
      name: 'SeaBank',
      role: 'Tabungan & Servis',
      type: 'bank',
      balance: 800_000,
      icon: 'account_balance',
    },
    {
      id: 'acct-bca',
      name: 'BCA Operasional',
      role: 'Kas Utama & QRIS',
      type: 'bank',
      balance: 1_428_000,
      icon: 'account_balance',
    },
    {
      id: 'acct-mandiri',
      name: 'Bank Mandiri',
      role: 'Tagihan Rutin',
      type: 'bank',
      balance: 150_000,
      icon: 'account_balance',
    },
    {
      id: 'acct-cash',
      name: 'Dompet Fisik / Tunai',
      role: 'Kas Saku Sehari-hari',
      type: 'cash',
      balance: 283_000,
      icon: 'payments',
    },
  ],

  billsDue: [
    {
      id: 'bill-wifi',
      name: 'WiFi Rumah (Indihome)',
      amount: 340_440,
      accountLabel: 'Mandiri',
      meta: 'Mandiri · Tenggat 23:59 WIB',
      badge: 'Tenggat 23:59 WIB',
      categoryLabel: 'Rutin Bulanan',
      icon: 'wifi',
      sourceAccountId: 'acct-mandiri',
      status: 'unpaid',
    },
    {
      id: 'bill-pln',
      name: 'Listrik PLN Pascabayar',
      amount: 275_000,
      accountLabel: 'BCA Payroll',
      meta: 'BCA Payroll · Tenggat 23:59 WIB',
      badge: 'Tenggat 23:59 WIB',
      categoryLabel: 'Pemakaian Rumah',
      icon: 'bolt',
      sourceAccountId: 'acct-bca',
      status: 'unpaid',
    },
  ],

  posItems: [
    {
      id: 'pos-darurat',
      name: 'Tabungan & Cadangan Darurat',
      description: 'Disimpan di: BCA / SeaBank',
      category: 'saving',
      accountLabel: 'BCA / SeaBank',
      amount: 3_500_000,
      targetAmount: 5_000_000,
      status: 'Aman terkendali',
      icon: 'shield',
    },
    {
      id: 'pos-organik',
      name: 'Simpanan Organik / Bebas',
      description: 'Simpanan cairan · Akumulasi fleksibel',
      category: 'saving',
      accountLabel: 'BCA Operasional',
      amount: 850_000,
      status: 'Akumulasi fleksibel',
      icon: 'account_balance_wallet',
    },
    {
      id: 'pos-makan',
      name: 'Dana Makan Mingguan',
      description: 'Rutinitas Bertahap · Plafon Rp 300.000',
      category: 'routine_incremental',
      accountLabel: 'SeaBank',
      amount: 200_000,
      plafon: 300_000,
      usedAmount: 100_000,
      cycleLabel: 'Plafon pekan ke-3 · Sisa 4 hari',
      status: '67% aman',
      icon: 'restaurant',
    },
    {
      id: 'pos-servis',
      name: 'Dana Servis Motor',
      description: 'Rutinitas Berkala · Servis Berkala',
      category: 'routine_batch',
      accountLabel: 'SeaBank',
      amount: 500_000,
      plafon: 500_000,
      cycle: 'Bulanan',
      status: '100% Siap',
      icon: 'two_wheeler',
    },
    {
      id: 'pos-kacamata',
      name: 'Dana Kacamata Baru',
      description: 'Sekali Pakai Non-Rutin',
      category: 'single_spend',
      accountLabel: 'BCA Operasional',
      amount: 400_000,
      targetAmount: 400_000,
      status: 'Siap Belanja',
      icon: 'visibility',
    },
    {
      id: 'pos-buku',
      name: 'Buku Bacaan & Belajar',
      description: 'Sekali Pakai',
      category: 'saving',
      accountLabel: 'BCA Operasional',
      amount: 120_000,
      targetAmount: 200_000,
      status: 'Sisa Rp 80.000',
      icon: 'menu_book',
    },
  ],

  agendas: [
    {
      id: 'agd-gaji',
      title: 'Gaji Pokok & Tunjangan',
      amount: 8_500_000,
      isIncome: true,
      displayDate: '25 Okt 2024',
      rawDate: '2024-10-25',
      accountLabel: 'Rekening BCA Payroll',
      categoryLabel: 'Pemasukan Kas',
      repeat: 'Bulanan',
      type: 'scheduled',
      icon: 'payments',
    },
    {
      id: 'agd-sewa',
      title: 'Sewa Studio Kerja',
      amount: 1_200_000,
      isIncome: false,
      displayDate: '28 Okt 2024',
      rawDate: '2024-10-28',
      accountLabel: 'Rekening Mandiri',
      categoryLabel: 'Biaya Operasional',
      repeat: 'Bulanan',
      type: 'scheduled',
      icon: 'business',
    },
    {
      id: 'agd-spotify',
      title: 'Langganan Spotify & Cloud',
      amount: 85_000,
      isIncome: false,
      displayDate: '30 Okt 2024',
      rawDate: '2024-10-30',
      accountLabel: 'Rekening SeaBank',
      categoryLabel: 'Langganan Digital',
      repeat: 'Bulanan',
      type: 'scheduled',
      icon: 'subscriptions',
    },
    {
      id: 'agd-donasi',
      title: 'Donasi Rutin Panti Asuhan',
      amount: 150_000,
      isIncome: false,
      displayDate: 'Kapan saja pekan ini',
      rawDate: '',
      accountLabel: 'Tunai / QRIS',
      categoryLabel: 'Donasi & Sosial',
      repeat: 'Mingguan',
      type: 'flexible',
      icon: 'volunteer_activism',
    },
    {
      id: 'agd-sembako',
      title: 'Belanja Sembako Bulanan',
      amount: 450_000,
      isIncome: false,
      displayDate: 'Awal Bulan',
      rawDate: '',
      accountLabel: 'Rekening BCA',
      categoryLabel: 'Belanja Dapur',
      repeat: 'Bulanan',
      type: 'flexible',
      icon: 'shopping_bag',
    },
    {
      id: 'agd-asuransi',
      title: 'Cicilan Asuransi Jiwa',
      amount: 450_000,
      isIncome: false,
      displayDate: '05 Nov 2024',
      rawDate: '2024-11-05',
      accountLabel: 'Rekening BCA',
      categoryLabel: 'Asuransi & Kewajiban',
      repeat: 'Bulanan',
      type: 'scheduled',
      icon: 'health_and_safety',
    },
    {
      id: 'agd-cloud',
      title: 'Langganan Cloud Storage',
      amount: 45_000,
      isIncome: false,
      displayDate: '08 Nov 2024',
      rawDate: '2024-11-08',
      accountLabel: 'Rekening Mandiri',
      categoryLabel: 'Langganan Digital',
      repeat: 'Bulanan',
      type: 'scheduled',
      icon: 'cloud',
    },
  ],

  archivedAgendas: [
    {
      id: 'arch-1',
      title: 'Iuran Sampah & Lingkungan',
      amount: 50_000,
      date: '02 Okt 2024',
      accountLabel: 'BCA Operasional',
      status: 'Selesai',
    },
    {
      id: 'arch-2',
      title: 'Langganan Cloud Backup',
      amount: 45_000,
      date: '05 Okt 2024',
      accountLabel: 'Bank Mandiri',
      status: 'Selesai',
    },
  ],

  transactions: [
    {
      id: 'tx-1',
      title: 'Sarapan Nasi Gudeg & Teh',
      accountLabel: 'BCA',
      accountId: 'acct-bca',
      date: 'Hari Ini 07:15',
      time: '07:15',
      dateGroup: 'Hari Ini — 24 Okt 2024',
      timePeriod: 'today',
      amount: -24_000,
      category: 'Konsumsi',
      icon: 'restaurant',
    },
    {
      id: 'tx-2',
      title: 'Kopi Susu Literan',
      accountLabel: 'BCA',
      accountId: 'acct-bca',
      date: 'Hari Ini 09:30',
      time: '09:30',
      dateGroup: 'Hari Ini — 24 Okt 2024',
      timePeriod: 'today',
      amount: -38_000,
      category: 'Makan',
      icon: 'local_cafe',
    },
    {
      id: 'tx-3',
      title: 'Top-up E-Money Tol',
      accountLabel: 'Mandiri',
      accountId: 'acct-mandiri',
      date: 'Hari Ini 11:20',
      time: '11:20',
      dateGroup: 'Hari Ini — 24 Okt 2024',
      timePeriod: 'today',
      amount: -100_000,
      category: 'Transportasi',
      icon: 'directions_car',
    },
    {
      id: 'tx-4',
      title: 'Beli Galon & Gas LPG',
      accountLabel: 'Tunai',
      accountId: 'acct-cash',
      date: 'Hari Ini 13:45',
      time: '13:45',
      dateGroup: 'Hari Ini — 24 Okt 2024',
      timePeriod: 'today',
      amount: -42_000,
      category: 'Konsumsi',
      icon: 'propane_tank',
    },
    {
      id: 'tx-5',
      title: 'Minimarket Sabun & Sikat Gigi',
      accountLabel: 'BCA',
      accountId: 'acct-bca',
      date: 'Kemarin 19:10',
      time: '19:10',
      dateGroup: 'Kemarin — 23 Okt 2024',
      timePeriod: 'week',
      amount: -36_500,
      category: 'Kebutuhan',
      icon: 'shopping_basket',
    },
    {
      id: 'tx-6',
      title: 'Bensin Pertamax Motor',
      accountLabel: 'Tunai',
      accountId: 'acct-cash',
      date: '22 Okt 2024, 16:30',
      time: '16:30',
      dateGroup: '22 Okt 2024',
      timePeriod: 'week',
      amount: -50_000,
      category: 'Transportasi',
      icon: 'local_gas_station',
    },
    {
      id: 'tx-7',
      title: 'Buku Catatan Grid A5',
      accountLabel: 'SeaBank',
      accountId: 'acct-seabank',
      date: '21 Okt 2024, 14:05',
      time: '14:05',
      dateGroup: '21 Okt 2024',
      timePeriod: 'week',
      amount: -65_000,
      category: 'Kebutuhan',
      icon: 'menu_book',
    },
    {
      id: 'tx-8',
      title: 'Terima Freelance Desain UI',
      accountLabel: 'BCA',
      accountId: 'acct-bca',
      date: '20 Okt 2024, 10:15',
      time: '10:15',
      dateGroup: '20 Okt 2024',
      timePeriod: 'week',
      amount: 1_250_000,
      category: 'Pemasukan',
      icon: 'arrow_downward',
    },
    {
      id: 'tx-9',
      title: 'Pangkas Rambut Rapih',
      accountLabel: 'Tunai',
      accountId: 'acct-cash',
      date: '19 Okt 2024, 15:40',
      time: '15:40',
      dateGroup: '19 Okt 2024',
      timePeriod: 'week',
      amount: -35_000,
      category: 'Kebutuhan',
      icon: 'content_cut',
    },
    {
      id: 'tx-10',
      title: 'Iuran Sampah RT & Lingkungan',
      accountLabel: 'Tunai',
      accountId: 'acct-cash',
      date: '16 Okt 2024, 08:00',
      time: '08:00',
      dateGroup: '16 Okt 2024',
      timePeriod: 'month',
      amount: -25_000,
      category: 'Rumah',
      icon: 'delete_outline',
    },
    {
      id: 'tx-11',
      title: 'Langganan Spotify Family',
      accountLabel: 'SeaBank',
      accountId: 'acct-seabank',
      date: '12 Okt 2024, 02:00',
      time: '02:00',
      dateGroup: '12 Okt 2024',
      timePeriod: 'month',
      amount: -54_990,
      category: 'Langganan',
      icon: 'music_note',
    },
    {
      id: 'tx-12',
      title: 'Makan Siang Soto Kudus',
      accountLabel: 'Mandiri',
      accountId: 'acct-mandiri',
      date: '10 Okt 2024, 12:15',
      time: '12:15',
      dateGroup: '10 Okt 2024',
      timePeriod: 'month',
      amount: -28_000,
      category: 'Makan',
      icon: 'restaurant',
    },
    {
      id: 'tx-13',
      title: 'Token Listrik Rumah',
      accountLabel: 'Mandiri',
      accountId: 'acct-mandiri',
      date: '08 Okt 2024, 08:30',
      time: '08:30',
      dateGroup: '08 Okt 2024',
      timePeriod: 'month',
      amount: -200_000,
      category: 'Rumah',
      icon: 'bolt',
    },
    {
      id: 'tx-14',
      title: 'Vitamin C & Masker Medis',
      accountLabel: 'BCA',
      accountId: 'acct-bca',
      date: '07 Okt 2024, 18:20',
      time: '18:20',
      dateGroup: '07 Okt 2024',
      timePeriod: 'month',
      amount: -45_000,
      category: 'Kebutuhan',
      icon: 'medical_services',
    },
    {
      id: 'tx-15',
      title: 'Internet & Wifi Fiber Bulanan',
      accountLabel: 'BCA',
      accountId: 'acct-bca',
      date: '06 Okt 2024, 10:00',
      time: '10:00',
      dateGroup: '06 Okt 2024',
      timePeriod: 'month',
      amount: -385_000,
      category: 'Rumah',
      icon: 'wifi',
    },
    {
      id: 'tx-16',
      title: 'Biji Kopi Arabika Specialty 250g',
      accountLabel: 'SeaBank',
      accountId: 'acct-seabank',
      date: '05 Okt 2024, 11:45',
      time: '11:45',
      dateGroup: '05 Okt 2024',
      timePeriod: 'month',
      amount: -95_000,
      category: 'Konsumsi',
      icon: 'coffee',
    },
    {
      id: 'tx-17',
      title: 'Laundry Kiloan Bedcover',
      accountLabel: 'Tunai',
      accountId: 'acct-cash',
      date: '04 Okt 2024, 14:10',
      time: '14:10',
      dateGroup: '04 Okt 2024',
      timePeriod: 'month',
      amount: -40_000,
      category: 'Rumah',
      icon: 'local_laundry_service',
    },
    {
      id: 'tx-18',
      title: 'Bagi Hasil Reksa Dana Pendapatan Tetap',
      accountLabel: 'Mandiri',
      accountId: 'acct-mandiri',
      date: '03 Okt 2024, 09:00',
      time: '09:00',
      dateGroup: '03 Okt 2024',
      timePeriod: 'month',
      amount: 410_000,
      category: 'Pemasukan',
      icon: 'trending_up',
    },
    {
      id: 'tx-19',
      title: 'Bibit Tanaman & Pupuk Kompos',
      accountLabel: 'Tunai',
      accountId: 'acct-cash',
      date: '02 Okt 2024, 16:50',
      time: '16:50',
      dateGroup: '02 Okt 2024',
      timePeriod: 'month',
      amount: -60_000,
      category: 'Rumah',
      icon: 'potted_plant',
    },
    {
      id: 'tx-20',
      title: 'Tiket Kereta Komuter KRL',
      accountLabel: 'Mandiri',
      accountId: 'acct-mandiri',
      date: '01 Okt 2024, 07:05',
      time: '07:05',
      dateGroup: '01 Okt 2024',
      timePeriod: 'month',
      amount: -16_000,
      category: 'Transportasi',
      icon: 'train',
    },
    {
      id: 'tx-21',
      title: 'Beras Organik Mentik 5kg',
      accountLabel: 'BCA',
      accountId: 'acct-bca',
      date: '30 Sep 2024, 10:20',
      time: '10:20',
      dateGroup: '30 Sep 2024',
      timePeriod: 'month',
      amount: -82_000,
      category: 'Makan',
      icon: 'shopping_cart',
    },
    {
      id: 'tx-22',
      title: 'Infaq & Sedekah Rutin',
      accountLabel: 'Tunai',
      accountId: 'acct-cash',
      date: '29 Sep 2024, 12:45',
      time: '12:45',
      dateGroup: '29 Sep 2024',
      timePeriod: 'month',
      amount: -50_000,
      category: 'Kebutuhan',
      icon: 'volunteer_activism',
    },
    {
      id: 'tx-23',
      title: 'Ganti Oli Mesin Berkala',
      accountLabel: 'BCA',
      accountId: 'acct-bca',
      date: '27 Sep 2024, 15:30',
      time: '15:30',
      dateGroup: '27 Sep 2024',
      timePeriod: 'month',
      amount: -68_000,
      category: 'Transportasi',
      icon: 'build',
    },
    {
      id: 'tx-24',
      title: 'Gaji Pokok Bulanan',
      accountLabel: 'Mandiri',
      accountId: 'acct-mandiri',
      date: '25 Sep 2024, 08:00',
      time: '08:00',
      dateGroup: '25 Sep 2024',
      timePeriod: 'month',
      amount: 6_800_000,
      category: 'Pemasukan',
      icon: 'savings',
    },
  ],

  savingsCommitment: 875_000,
};
